server:
  port: 8083
spring:
  application:
    name: microservice-gateway-zuul
  jmx:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@134.175.134.80:8080/eureka/,http://user:123456@193.112.89.97:8080/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    microservice-provider-user: user/**