server:
  port: 8095
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          clone-on-start: true     #启动时即clone配置文件
          uri: https://github.com/csuzxm2003/springcloud-config.git      # 配置Git仓库的地址
          username:                                               # Git仓库的账号
          password:                                              # Git仓库的密码
  rabbitmq:
    host: 134.175.134.80
    port: 5672
    username: root
    password: dhcc2018
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8080/eureka/
  instance:
    prefer-ip-address: false

logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: debug