server:
  port: 8082
spring:
  application:
    name: gateway
  jmx:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8080/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    service-provider-A: providerA/**
    service-provider-B: providerB/**
    service-client: client/**
    service-config: config/**